Testing Toolbox: Log if the installation of the operators succeeded

diff --git a/tools/testing-toolbox/templates/test.sh.j2 b/tools/testing-toolbox/templates/test.sh.j2
--- a/tools/testing-toolbox/templates/test.sh.j2
+++ b/tools/testing-toolbox/templates/test.sh.j2
@@ -25,8 +25,14 @@ cd {{ testsuite.git_repo }}
 
 # Install the Stackable Data Platform release
 retry --delay=60 --times=10 \
-    python scripts/run-tests --skip-tests {{ test_params }} \
-    || exit 1
+    sh -c "printf '[%(%F %T)T] Trying to install the operators ...\n'; python scripts/run-tests --skip-tests {{ test_params }}"
+exit_code=$?
+if [ $exit_code -ne 0 ]; then
+    printf '[%(%F %T)T] Installation of the operators failed.\n'
+    exit 1
+else
+    printf '[%(%F %T)T] Operators successfully installed.\n'
+fi
 
 # Tests want to know where to pipe their logs to
 export VECTOR_AGGREGATOR=vector-aggregator.t2-cluster-logging.svc.cluster.local:6000
