Retry the installation of the SDP release on failure

diff --git a/tools/testing-toolbox/templates/test.sh.j2 b/tools/testing-toolbox/templates/test.sh.j2
--- a/tools/testing-toolbox/templates/test.sh.j2
+++ b/tools/testing-toolbox/templates/test.sh.j2
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Wait for the cluster to be REALLY ready
+# Wait for the cluster to be ready
 kubectl wait --for=condition=Ready nodes --all --timeout=10m
 kubectl wait --for=condition=Ready pods --namespace kube-system --all --timeout=10m
 
@@ -21,14 +21,23 @@ git clone https://github.com/stackabletech/{{ testsuite.git_repo }}.git
 {% for helm_repo in testsuite.helm_repos %}helm repo add {{ helm_repo.id }} {{ helm_repo.url }}
 {% endfor %}
 
+cd {{ testsuite.git_repo }}
+
+# Install the Stackable Data Platform release
+# TODO Implement a proper solution instead of calling a non-existent test, if this fixes the following error:
+# helm FFI library call failed (failed to install CRD crds/crds.yaml: 1 error occurred:
+#   * Post "https://cp-bcfbddf8-4dc4-4165-99c4-859a04ddb0ba.cluster.ionos.com:13592/apis/apiextensions.k8s.io/v1/customresourcedefinitions?fieldManager=stackablectl": unexpected EOF
+retry --delay=60 --times=10 \
+    python scripts/run-tests --test install-release-only {{ test_params }} \
+    || exit 1
 
 # Tests want to know where to pipe their logs to
 export VECTOR_AGGREGATOR=vector-aggregator.t2-cluster-logging.svc.cluster.local:6000
 
 {% if beku_suite %}
-(cd {{ testsuite.git_repo }}/ && python ./scripts/run-tests --log-level debug --test-suite {{ beku_suite }} {{ test_params }})
+python scripts/run-tests --log-level debug --skip-release --test-suite {{ beku_suite }} {{ test_params }}
 {% else %}
-(cd {{ testsuite.git_repo }}/ && python ./scripts/run-tests --log-level debug {{ test_params }})
+python scripts/run-tests --log-level debug --skip-release {{ test_params }}
 {% endif %}
 
 exit_code=$?
